#!/usr/bin/env bash

COMMAND=""
A_FILTER=""
B_FILTER=""
IP_FILTER=""
URI_FILTER=""
#hladame filtre
while(("$#" > 0)); do 
        case $1 in
        -a)
            # hodnota -a ide do A_FILTER a preskakujeme -a, hodnotu  cize shift2
            A_FILTER="$2"
            shift 2
            ;;
        -b) 
            B_FILTER="$2"
            shift 2
            ;;
        -ip)
            IP_FILTER="$2"
            shift 2
            ;;
        -uri)
            URI_FILTER="$2"
            shift 2
            ;;
        list-ip|list-hosts|list-uri|hist-ip|hist-load)
            #zapametavame si comand a preskakujeme
            COMMAND="$1"
            shift 1
            break
            ;;
        *)
            #reachneme file
            break
        
    esac  
done


list_ip() {
    #berieme cely riadok, cutneme na iba prvy element, sortneme a vypiseme iba unikatne ip adresy
        awk '{print $1}' | sort -u

}
list_hosts(){
    # berieme ip adresu, posielame do whilu
        awk '{print $1}' | sort -u | while read -r ip_adress; do
        # zapisujeme si host name a zistujeme ci je valid cez grpe
        host_name=$(host "$ip_adress")
        if echo "$host_name" | grep -q "NXDOMAIN"; then
            echo "$ip_adress"
        else 
        #ak je valid berieme 5. parameter 
            echo "$host_name" | awk '{print $5}'
        fi
    done | sort -u
}
list_uri(){
    #berieme poziciu na ktorej byva uri, posielame do whilu
        awk '{print $6,$7}' | sort -u | while read -r check uri ; do 
        #premena check sleduje ci je v tom riadku "-" co by znamenalo ze nema uri 
        if [ "$check" != '"-"' ] && [ -n "$uri" ]; then
            echo "$uri"
        fi
    done | sort -u

}
hist_ip(){
        awk '{print $1}' | sort | uniq -c | sort -nr | while read -r count ip; do
        echo -n "$ip ($count): "
        for (( i =0;i<count;i++ )); do
            echo -n "#"
        done
        echo
    done
}

hist_load(){
        awk '{print $4}' | awk -F ':' '{print $1,$2}'| sort | uniq -c | while read -r count date time; do
        #upravujeme datum aby sa dal previest na date format
        # menime  '/' za '-'
        date=$(echo "$date"| sed 's/\//-/g')
        #zbavujeme sa '[' na zaciatku riadku
        date=$(echo "$date"| sed 's/\[//g') 
        #prevadzame datumy na den,datum,rok 
        day=$(echo "$date" | awk -F '-' '{print $1}')

        month=$(echo "$date" | awk -F '-' '{print $2}')
        year=$(echo "$date" | awk -F '-' '{print $3}')
        case ${month,,} in 
            jan)
                month=01
                ;;
            feb)
                month="02"
                ;;               
            mar)
                month=03
                ;;
            apr)
                month=04
                ;;
            may)
                month=05
                ;;
            jun)
                month=06
                ;;
            jul)
                month=07
                ;;
            aug)
                month=08
                ;;
            sep)
                month=09
                ;;
            oct)
                month=10
                ;;
            nov)
                month=11
                ;;   
            dec)
                month=12
                ;;
            *)
                echo "invalid date"
        esac                                                                          
        echo -n "$year-$month-$day $time:00 ($count): "
        for (( i =0;i<count;i++ )); do  
            echo -n "#"
        done
        echo
    done | sort
}
filters(){
    #prepocitame si filtre na sekundy od epochy  ak boli zadanie
    if [ -n "$A_FILTER" ]; then
        A_FILTER=$(date -d "$A_FILTER" +%s)
    fi
    if [ -n "$B_FILTER" ]; then
        B_FILTER=$(date -d "$B_FILTER" +%s) 
    fi
    #zacneme uri a ip filtrami, lebo sa daju pekne spojit, prazdny grep nerobi nic cize mozu ist za sebou
    # a potom tie riadky posielame do whilu kde sa ideme hrat s datumami
    #zcat lebo tam su zazipovane subory v tych test srandach
    zcat -f "$@" | grep "$IP_FILTER" | grep "$URI_FILTER" | while read -r line ; do
        # konvertujeme datum z fajlu do datumu ktory vie potom funkcia date precitat
        # menime / za - , a zbavujeme sa prvej :  , ktora je medzi rokom a casom, a zbavujeme sa '['
        date=$(echo "$line"| awk '{print $4}' | sed 's/\//-/g')
        date=$(echo "$date" | sed 's/\[//')
        date=$(echo "$date" | sed 's/:/ /')
        date=$(date -d "$date" +%s)
        if [ -n "$A_FILTER" ] && [ "$A_FILTER" -ge "$date" ]; then
            continue
        fi
        if [ -n "$B_FILTER" ] && [ "$B_FILTER" -le "$date" ]; then
            continue
        fi
        echo "$line"
    done

    
}

case $COMMAND in
    list-ip)
        filters "$@" | list_ip 
        ;;
    list-hosts) 
        filters "$@" | list_hosts
        ;;
    list-uri)
        filters "$@" | list_uri 
        ;;
    hist-ip)
        filters "$@" | hist_ip 
        ;;
    hist-load)
        filters "$@" | hist_load 
        ;;
    "")
        filters "$@" | cat 
        ;;
    *)
        echo "wrong first parameter used"
esac